/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package wdk;

/**
 *
 * @author Work
 */
public enum GeneralPropertyType implements WDK_PropertyType {
   //LOADED FROM properties.xml
//LOADED FROM properties.xml
//LOADED FROM properties.xml
//LOADED FROM properties.xml
    PROP_APP_TITLE,
    
    // APPLICATION ICONS
    
    NEW_DRAFT_ICON,
    LOAD_DRAFT_ICON,
    SAVE_DRAFT_ICON,
    EXPORT_DRAFT_ICON,
    DELETE_ICON,
    EXIT_ICON,
    ADD_ICON,
    MINUS_ICON,
    EDIT_ICON,
    
    BLANK_IMAGE,
    DEFAULT_FLAG,
    
    
    // Application Tooltips for various buttons
    NEW_DRAFT_TOOLTIP,
    LOAD_DRAFT_TOOLTIP,
    SAVE_DRAFT_TOOLTIP,
    VIEW_SCHEDULE_TOOLTIP,
    EXPORT_DRAFT_TOOLTIP,
    DELETE_TOOLTIP,
    EXIT_TOOLTIP,
    ADD_PLAYER_TOOLTIP,
    REMOVE_PLAYER_TOOLTIP,
    ADD_TEAM_TOOLTIP,
    REMOVE_TEAM_TOOLTIP,
    EDIT_TEAM_TOOLTIP,
    DRAFT_HEADING_LABEL,
    DRAFT_INFO_LABEL,
    PLAYER_NAME_LABEL,
    PLAYER_AGE_LABEL,
    PLAYER_NATIONALITY_LABEL,
    PLAYER_NOTES_LABEL,
    TEAM_NAME_LABEL,
    TEAM_OWNER_LABEL,
    
    
    PLAYERS_SCREEN_TOOLTIP,
    FANTASY_TEAMS_SCREEN_TOOLTIP,
    FANTASY_STANDINGS_SCREEN_TOOLTIP,
    DRAFT_SCREEN_TOOLTIP,
    SPORT_SCREEN_TOOLTIP,
    
    
    
    //ERROR MESSAGES MORE TO COME
    
    NOT_A_VALID_AGE_MESSAGE,
    SAME_PLAYER_NAME_MESSAGE,
    SAME_TEAM_NAME_MESSAGE,
    CLOSE_BUTTON_TEXT,
    
    
    //VERIFICATION MESSAGES
    NEW_DRAFT_CREATED_MESSAGE,
    DRAFT_LOADED_MESSAGE,
    DRAFT_SAVED_MESSAGE,
    DRAFT_EXPORTED_MESSAGE,
    SAVE_UNSAVED_WORK_MESSAGE,
    REMOVE_PLAYER_MESSAGE,
    REMOVE_TEAM_MESSAGE,
   
    //AVAILABLE PLAYERS TAGS
    AVAILABLE_PLAYER_LABEL,
    PLAYER_SEARCH_LABEL, 
    PLAYERS_ICON, 
    
    
    //FANTASY TEAMS TAG
    FANTASY_TEAMS_LABEL,
    TEAM_SELECT_LABEL,
  //TEAM_NAME_LABEL  
  //TEAM_OWNER_LABEL  
    
    FANTASY_STANDINGS_LABEL,
    DRAFT_SUMMARY_LABEL,
    SPORT_LABEL,
    
    FANTASY_TEAMS_ICON, 
    FANTASY_STANDINGS_ICON, 
    DRAFT_ICON, 
    SPORT_ICON, 
    MLB_TEAMS_LABEL, 
    
    
    // DRAFT SCREEN TAG
    DRAFT_BEST_PLAYER_TOOLTIP,
    START_AUTOMATED_DRAFT_TOOLTIP,
    PAUSE_AUTOMATED_DRAFT_TOOLTIP, 
    START_ICON,
    PAUSE_ICON,  
    
    
    //DIALOG TAG
    DIALOG_TEAM_LABEL,
    DIALOG_POSITION_LABEL,
    DIALOG_CONTRACT_LABEL,
    DIALOG_SALARY_LABEL
    
}
